apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: http-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: http-app 
  name: http-app
  namespace: app-demo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: http-app 

