apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a-service 
  name: a-service
  namespace: app-demo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: a-service 

